#!/bin/bash
### BEGIN INIT INFO
# Provides:          xmrig-proxy
# Required-Start:    $all
# Required-Stop:     
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: xmrig-proxy.
# Description:       xmrig-proxy daemon.
### END INIT INFO
 
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# xmrig-proxy程序文件，请根据位置进行修改
DAEMON='/root/xmrig-proxy/build/xmrig-proxy'
# xmrig-proxy配置信息文件，请根据位置进行修改
CONFIG='/root/xmrig-proxy/build/config.json'
# 本启动文件所在位置
StartFile='/root/xmrig-proxy'
 
test -x $DAEMON || exit 0
[ -f $CONFIG ] || exit 0
 
stop_daemon(){
  /usr/bin/kill -9 $(ps -C "$(basename $DAEMON)") >/dev/null 2>&1
}
 
case "$1" in
  start)
    stop_daemon;
    screen -Sdm xmrig-proxy $DAEMON -c $CONFIG
    ;;
  stop)
    stop_daemon;
    ;;
  restart)
    stop_daemon;
	sleep 3;
	screen -Sdm xmrig-proxy $DAEMON -c $CONFIG
    ;;
  init)
    LIMIT='512000'
    ulimit -n $LIMIT
    chmod 755 $StartFile
    ln -sf $StartFile /etc/init.d/xmrig-proxy
    if [[ -f /etc/security/limits.conf ]]; then
      sed -i '/^\(\*\|root\).*\(hard\|soft\).*nofile/d' /etc/security/limits.conf
      echo -ne "*\thard\tnofile\t$LIMIT\n*\tsoft\tnofile\t$LIMIT\nroot\thard\tnofile\t$LIMIT\nroot\tsoft\tnofile\t$LIMIT\n" >> /etc/security/limits.conf
    fi
	grep "* soft memlock 262144" /etc/security/limits.conf
    if [ $? -ne 0 ]; then
	  echo "* soft memlock 262144" >> /etc/security/limits.conf
	  echo "* hard memlock 262144" >> /etc/security/limits.conf
    fi
    if [[ -f /etc/sysctl.conf ]]; then
      sed -i '/^fs.file-max.*/d' /etc/sysctl.conf
      sed -i '/^vm.nr_hugepages.*/d' /etc/sysctl.conf
      echo -ne '\nvm.nr_hugepages=128\n' >>/etc/sysctl.conf
      echo -ne '\nfs.file-max=512000\n' >>/etc/sysctl.conf
    fi
	# centos6 开机启动
	#chkconfig --level xmrig-proxy 2345 on
	# ubuntu debian开机启动
    #update-rc.d -f xmrig-proxy remove
    #update-rc.d -f xmrig-proxy defaults
    sysctl -p >/dev/null
    ;;
  *)
    echo "Usage: bash $StartFile {start|stop|restart|init}" >&2
    exit 1
    ;;
esac
 
exit 0